services:
  # MariaDB
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    expose:
      - 3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - project-network

  # PHP-FPM
  php-01:
    image: php:8.3-fpm
    container_name: php-01
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - ./app-php-01:/srv/app
      - ./config/php-01/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    working_dir: "/srv/app"
    networks:
      - project-network

  # nginx
  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app-php-01:/srv/app-php-01:ro
      - ./backend-01:/srv/app-backend-01:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - project-network

  # backend-01
  backend-01:
    build:
      context: ./
      dockerfile: Dockerfile.backend-01
    container_name: backend-01
    restart: unless-stopped
    env_file:
      # default environment variables
      - path: ./backend-01/.env
        required: true
      # local environment variables (override defaults when needed)
      - path: ./backend-01/.env.local
        required: false
    expose:
      - 9000
    volumes:
      - ./backend-01:/srv/app
    working_dir: "/srv/app"
    networks:
      - project-network

networks:
  project-network:
    external: true
