version: '3.8'

services:
  # MariaDB 
  mariadb:
    image: mariadb:10.6
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # PHP-FPM 
  php:
    image: php:8.2-fpm
    container_name: php
    restart: unless-stopped
    volumes:
      - ./backend1:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    depends_on:
      - mariadb

  # nginx 
  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend1:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - php

  # backend1 
  backend1:
    build: ./backend1
    container_name: backend1
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend1:/app
    environment:
      - DB_HOST=mariadb
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASS=userpassword
    networks:
      - app-network
    depends_on:
      - mariadb

volumes:
  db_data:

networks:
  app-network:
    driver: bridge